services:
  zmk-build:
    build: .
    volumes:
       - ./output:/workspace/output
       - ./config:/workspace/config
       - ./build.sh:/workspace/build.sh
       - ./build.yaml:/workspace/build.yaml
    environment:
      - ZMK_CONFIG=/workspace/config
    entrypoint: ["/workspace/build.sh"]
