draw_config:
  dark_mode: true
  separate_combo_diagrams: true
  append_colon_to_layer_header: false
parse_config:
  raw_binding_map:
    "&bootloader": "boot"
    "&base_layer": "base"
    "&home": "asdf;lkj"
    "&mkp MB1": "Mouse Left"
    "&mkp MB2": "Mouse Right"
    "&mkp MB3": "Mouse Wheel"
    "&mkp MB4": "Mouse Back"
    "&mkp MB5": "Mouse Forward"
    "&mkp_2mb1": "Double Click"
    "&mkp_3mb1": "Triple Click"
    "&bt BT_SEL 0": "ᛒ1"
    "&bt BT_SEL 1": "ᛒ2"
    "&bt BT_SEL 2": "ᛒ3"
    "&bt BT_SEL 3": "ᛒ4"
    "&bt BT_SEL 4": "ᛒ5"
    "&bt BT_CLR": "ᛒx"
    "&out OUT_TOG": "ᛒ/ψ"
    "&hkp RWIN UP": "Win ↑"
    "&hkp RWIN DOWN": "Win ↓"
    "&hkp RWIN LEFT": "Win ←"
    "&hkp RWIN RIGHT": "Win →"
    "&hkp RC(RGUI) LEFT": "Ctrl Win ←"
    "&hkp RS(RGUI) LEFT": "Shift Win ←"
    "&hkp RC(RGUI) RIGHT": "Ctrl Win →"
    "&hkp RS(RGUI) RIGHT": "Shift Win →"
  mark_alternate_layer_activators: true
  modifier_fn_map:
    left_ctrl: Ctrl
    right_ctrl: Ctrl
    left_shift: Shift
    right_shift: Shift
    left_alt: Alt
    right_alt: Alt
    left_gui: Win
    right_gui: Win
    mod_combiner: "{mod_1} {mod_2}"
    keycode_combiner: "{mods} {key}"
  zmk_keycode_map:
    SEMI: ";+"
    COMMA: ",<"
    DOT: ".>"
    SLASH: "/?"
    GRAVE: "半/全"
    SPACE: "␣"
    TAB: "↹"
    ENTER: "⏎"
    INT2: "あ/ア"
    MINUS: "-="
    EQUAL: "^~"
    INT3: "\\|"
    LEFT: "←"
    DOWN: "↓"
    UP: "↑"
    RIGHT: "→"
    HOME: "↖"
    PG_DN: "⤒"
    PG_UP: "⤓"
    END: "↘"
    PSCRN: "⎙"
    SLCK: "⇳"
    PAUSE_BREAK: "⎉"
    INS: "⭿"
    BSPC: "⌫"
    DEL: "⌦"
    K_APP: "≣"
    N1: "1!"
    N2: "2\""
    N3: "3#"
    N4: "4$"
    N5: "5%"
    N6: "6&"
    N7: "7'"
    N8: "8("
    N9: "9)"
    KP_SLASH: "(/)"
    KP_ASTERISK: "(*)"
    KP_MINUS: "(-)"
    KP_PLUS: "(+)"
    KP_DOT: "(.)"
    SQT: ":*"
    LBKT: "@`"
    RBKT: "[{"
    NUHS: "]}"
    INT1: "\\_"
    C_VOL_UP: "🔊"
    C_VOL_DN: "🔉"
    C_MUTE: "🔇"
    LCTRL: "Ctrl"
    LSHFT: "Shift"
    LALT: "Alt"
    LGUI: "Win"
    RCTRL: "Ctrl"
    RSHFT: "Shift"
    RALT: "Alt"
    RGUI: "Win"
