draw_config:
  dark_mode: true
  separate_combo_diagrams: true
  append_colon_to_layer_header: false
parse_config:
  raw_binding_map:
    "&base_layer": "BASE"
    "&bootloader": "BOOT"
    "&home": "asdf;lkj"
    "&mkp MB1": "Mouse Button1"
    "&mkp MB2": "Mouse Button2"
    "&mkp MB3": "Mouse Button3"
    "&mkp MB4": "Mouse Button4"
    "&mkp MB5": "Mouse Button5"
    "&mkp_2mb1": "Double Click"
    "&mkp_3mb1": "Triple Click"
    "&bt BT_SEL 0": "BT0 SELECT"
    "&bt BT_SEL 1": "BT1 SELECT"
    "&bt BT_SEL 2": "BT2 SELECT"
    "&bt BT_SEL 3": "BT3 SELECT"
    "&bt BT_SEL 4": "BT4 SELECT"
  mark_alternate_layer_activators: true
  modifier_fn_map:
    left_ctrl: Ctrl
    right_ctrl: Ctrl
    left_shift: Shift
    right_shift: Shift
    left_alt: Alt
    right_alt: Alt
    left_gui: Win
    right_gui: Win
    keycode_combiner: '{mods} {key}'
  zmk_keycode_map:
    SEMI: ';+'
    COMMA: ',<'
    DOT: '.>'
    SLASH: '/?'
    GRAVE: '半/全'
    SPACE: '␣'
    TAB: '↹'
    ENTER: '⏎'
    INT2: 'あ/ア'
    MINUS: '-='
    EQUAL: '^~'
    INT3: '\|'
    LEFT: '←'
    DOWN: '↓'
    UP: '↑'
    RIGHT: '→'
    HOME: '↖'
    PG_DN: '⤒'
    PG_UP: '⤓'
    END: '↘'
    PSCRN: '⎙'
    SLCK: '⇳'
    PAUSE_BREAK: '⎉'
    INS: 'Ins'
    BSPC: '⌫'
    DEL: '⌦'
    K_APP: '≣'
    N1: '1!'
    N2: '2"'
    N3: '3#'
    N4: '4$'
    N5: '5%'
    N6: '6&'
    N7: '7'''
    N8: '8('
    N9: '9)'
    KP_SLASH: '(/)'
    KP_ASTERISK: '(*)'
    KP_MINUS: '(-)'
    KP_PLUS: '(+)'
    KP_DOT: '(.)'
    SQT: ':*'
    LBKT: '@`'
    RBKT: '[{'
    NUHS: ']}'
    INT1: '\_'
