name: Build ZMK firmware

on:
  push:
    paths:
      - 'config/**'
  workflow_dispatch:

jobs:
  build:
    uses: skubmdi/docker-zmk-builder/.github/workflows/publish-builder-iamge.yml@sandbox
