name: Build ZMK firmware

on:
  push:
    paths:
      - 'config/**'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
    with:
      archive_name: ${{ github.sha }}
